addiction_app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from authentication import urls as urls_auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.general.urls')),
    path('', include('apps.authentication.urls')),
    path('forum/', include('apps.forum.urls')),
    path('messages/', include('apps.communication.urls')),
    path('paths/', include('apps.quitpath.urls')),
    path('specialists/', include('apps.specialists.urls')),
    path('motivations/', include('apps.motivation.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ChainBreak'

apps/communication/urls.py
from django.urls import path
from apps.communication import views

urlpatterns = [
    path('', views.messages, name='messages'),
    path('new', views.new_message, name='new_message'),
    path('<int:user_id>/', views.show, name='show'),
]

apps/communication/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    content = models.CharField(max_length=1000)
    shipper = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='shipper')
    receiver = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='receiver')
    created_at = models.DateTimeField(auto_now=True)
    seen = models.BooleanField(default=False)

apps/communication/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Message


class NewMessageForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': '4',
            'cols': '40',
            'placeholder': 'Treść wiadomości',
            'class': 'form-control'
        }))
    receiver = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Odbiorca',
            'class': 'form-control'
    }))

    class Meta:
        model = Message
        fields = ('content', 'receiver')

    def clean_content(self):
        content = self.cleaned_data['content']

        if len(content) < 1:
            raise forms.ValidationError('Zawartość wiadomości nie może być pusta')

        return content

    def clean_receiver(self):
        receiver = self.cleaned_data['receiver']

        try:
            user = User.objects.get(username=receiver)
        except:
            raise forms.ValidationError('Nie ma takiego użytkownika')

        return user

    def send_message(self, shipper):
        message = Message.objects.create(
            content=self.cleaned_data['content'], 
            shipper=shipper, 
            receiver=self.cleaned_data['receiver']
        )
        return message

apps/communication/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import redirect, render, HttpResponseRedirect, get_object_or_404

from apps.quitpath.utils import create_notification
from .models import Message
from .forms import NewMessageForm


@login_required
def messages(request):
    conversations = []

    for user in User.objects.all():
        sent = Message.objects.filter(shipper=request.user, receiver=user)
        received = Message.objects.filter(shipper=user, receiver=request.user)

        if len(sent) > 0 or len(received) > 0:
            date = max(message.created_at for message in sent | received)
            conversations.append({
                'user': user,
                'count': len(received.filter(seen=False)),
                'date': date,
            })

    from operator import itemgetter
    conversations = sorted(conversations, key=itemgetter('date'), reverse=True)

    context = {
        'conversations': conversations
    }

    return render(request, 'messages.html', context)


@login_required
def new_message(request):
    context = {}
    user = request.user

    if request.method == "POST":
        form = NewMessageForm(request.POST)
        if form.is_valid():
            message = form.send_message(user)

            text = 'Nowa wiadomość:<br>od <b>{}</b>'.format(request.user.username)
            url = reverse('show', kwargs={'user_id': request.user.pk})
            create_notification(user=message.receiver, text=text, url=url)

            return redirect('/messages/{}/'.format(message.receiver.pk))
    else:
        form = NewMessageForm()

    context.update({
        'form': form
    })
    return render(request, 'new.html', context)


@login_required
def show(request, user_id):
    other_user = get_object_or_404(User, pk=user_id)

    sent = Message.objects.filter(shipper=request.user.pk, receiver=user_id)
    received = Message.objects.filter(shipper=user_id, receiver=request.user.pk)

    for message in received:
        if message.seen is False:
            message.seen = True
            message.save()

    messages = sorted(sent | received, key=lambda message: message.created_at)

    context = {
        'messages': messages,
        'other_user': other_user,
    }

    if request.method == "POST":
        message = Message()
        message.content = request.POST['content']
        message.shipper = request.user
        message.receiver = other_user
        message.save()

        text = 'Nowa wiadomość:<br>od <b>{}</b>'.format(request.user.username)
        url = reverse('show', kwargs={'user_id': request.user.pk})
        create_notification(user=other_user, text=text, url=url)

        return HttpResponseRedirect(reverse('show', kwargs={'user_id': user_id}))

    return render(request, 'show.html', context)

apps/communication/templates/messages.html
{% extends 'base.html' %}

{% block title %}Wiadomości{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12 clearfix">
            <div class="float-left ml-3">
                <h1>Wiadomości</h1>
            </div>
            <div class="float-right mr-3">
                <a href="{% url 'new_message' %}" class="btn btn-info float-right">
                    Nowa wiadomość
                </a>
            </div>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="offset-2 col-md-8 messages">
            {% if conversations %}
                {% for item in conversations %}
                    <a class="text-dark message" href="{% url 'show' user_id=item.user.pk %}">
                        <div class="card bg-light mb-3">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    {{ item.user.username }}
                                    <div class="float-right">
                                        {% if item.count != 0 %} Nowych:
                                            <span class="badge badge-pill badge-info">{{ item.count }}</span> {% endif %}
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <h1>Brak konwersacji</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script>
        $(function () {
            $('.card').hover(function () {
                $(this).removeClass('bg-light');
                $(this).addClass('bg-secondary');
            }, function () {
                $(this).removeClass('bg-secondary');
                $(this).addClass('bg-light');
            });
        })
    </script>
{% endblock %}

apps/communication/templates/new.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}ChainBreak - Wiadomości{% endblock %}

{% block head_additional_data %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css"
          integrity="sha256-sJQnfQcpMXjRFWGNJ9/BWB1l6q7bkQYsRqToxoHlNJY=" crossorigin="anonymous"/>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8 offset-2">
            <h1>Nowa wiadomość</h1>
        </div>
    </div>

    <hr/>

    <div class="row">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="col-10 offset-1 alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <div class="col-8 offset-2">
            <form method="post" action="{% url 'new_message' %}">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.receiver|add_class:"col-4" }}
                    {{ form.content }}
                </div>

                <input class="btn btn-info form-control" type="submit" value="Wyślij wiadomość">
            </form>
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"
            integrity="sha256-BEqTcxuDdEftl1gxpORMY6kS6tR8RJIL3WxfXKKTI+g=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/i18n/defaults-pl_PL.min.js"
            integrity="sha256-a8y8p6EEetJRzoR49sBNNobCkDZlv0tefH6RQW05dVQ=" crossorigin="anonymous"></script>
{% endblock %}

apps/communication/templates/show.html
{% extends 'base.html' %}

{% block title %}ChainBreak - Wiadomości z {{ other_user.username }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="offset-1 col-md-10">
            <a class="btn btn-info" href="{% url 'messages' %}">Wróć do wiadomości</a><br><br>
            <div class="top-buffer"></div>
            <div class="card">
                <div class="card-header">
                    <strong>Konwersacja z: {{ other_user.username }}</strong>
                </div>
                <ul class="list-group list-group-flush">
                    {% for message in messages %}
                        <li class="list-group-item">
                            {% if message.shipper.pk == user.pk %}
                                <div class="container">
                                    <div class="offset-5 col-md-7 message-sent"
                                         style="background-color: #2d7eff; color: white; padding: 10px 20px 25px 20px; border-radius: 15px;">
                                        <b>Ja:</b> {{ message.content }}
                                        <br>
                                        <div class="float-right" style="font-size: 12px;">
                                            <b>{{ message.created_at|date:"H:i d.m.y" }}</b></div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="container">
                                    <div class="col-md-7 message-received"
                                         style="background-color: #dadada; padding: 10px 20px 25px 20px; border-radius: 15px;">
                                        <b>{{ other_user.username }}:</b> {{ message.content }}
                                        <br>
                                        <div class="float-right" style="font-size: 12px;">
                                            <b>{{ message.created_at|date:"H:i d.m.y" }}</b></div>
                                    </div>
                                </div>
                            {% endif %}
                        </li>
                    {% endfor %}
                    <li class="list-group-item">
                        <div id="scroll-to-form" class="container form-group">
                            <form method="post" action="{% url 'show' user_id=other_user.pk %}">{% csrf_token %}
                                <textarea name="content" id="id_content" placeholder="Treść wiadomości" required=""
                                          cols="40" rows="4" class="form-control"
                                          style="width: 100%; border-bottom-right-radius: 0; margin-bottom: -1px;"></textarea>
                                <input type="submit" value="Odpowiedz" class="float-right btn btn-outline-primary"
                                       style="border-top-right-radius: 0; border-top-left-radius: 0;">
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block additional_js %}
    <script>
        window.onload = function () {
            window.scrollTo(0, document.body.scrollHeight);
        }
    </script>
{% endblock %}