addiction_app/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from authentication import urls as urls_auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.general.urls')),
    path('', include('apps.authentication.urls')),
    path('forum/', include('apps.forum.urls')),
    path('messages/', include('apps.communication.urls')),
    path('paths/', include('apps.quitpath.urls')),
    path('specialists/', include('apps.specialists.urls')),
    path('motivations/', include('apps.motivation.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ChainBreak'

apps/quitpath/urls.py
from django.urls import path
from apps.quitpath import views

urlpatterns = [
    path('', views.paths, name='paths'),
    path('new', views.new_path, name='new_path'),
    path('quitpath/<int:id>', views.quitpath, name='quitpath'),
    path('gettime/<int:id>', views.gettime, name='gettime'),
    path('delete_breakpoint/<int:quitpath_id>/<int:breakpoint_id>', views.delete_breakpoint, name='delete_breakpoint'),
    path('get_best_trophy/<int:id>', views.get_best_trophy, name='get_best_trophy'),
    path('delete_quitpath/<int:id>', views.delete_quitpath, name='delete_quitpath')
]

apps/quitpath/models.py
from django.db import models
from django.contrib.auth.models import User


class Addiction(models.Model):
    name = models.CharField(max_length=1000)
    icon = models.ImageField(upload_to='addictions_icons/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Nałóg'
        verbose_name_plural = 'Nałogi'


class Quitpath(models.Model):
    begin_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quitpath_user')
    addiction = models.ForeignKey(Addiction, on_delete=models.CASCADE, related_name='quitpath_addiction')
    last_breakpoint_date = models.DateTimeField(auto_now_add=False)
    motive = models.TextField()

    def __str__(self):
        return 'quitpath_{}'.format(self.pk)

    class Meta:
        verbose_name = 'Ścieżka'
        verbose_name_plural = 'Ścieżki'


class Trophy(models.Model):
    name = models.CharField(max_length=100)
    time = models.PositiveIntegerField(default=0)
    quitpath = models.ForeignKey(Quitpath, on_delete=models.CASCADE, related_name='trophy_quitpath')
    icon = models.CharField(max_length=100, default='')
    achieved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Trofeum'
        verbose_name_plural = 'Trofea'


class Breakpoint(models.Model):
    date = models.DateTimeField(auto_now_add=False)
    quitpath = models.ForeignKey(Quitpath, on_delete=models.CASCADE, related_name='breakpoint_quitpath')

    def __str__(self):
        return '{}-{}-{}'.format(self.date.day, self.date.month, self.date.year)

apps/quitpath/forms.py
from django import forms
from datetime import datetime

from django.utils.html import format_html

from apps.quitpath.models import Quitpath, Addiction, Breakpoint, Trophy
from apps.quitpath.utils import prepare_trophies


def leading_zero(number: int):
    return '{}{}'.format('' if number > 9 else '0', number)


class QuitpathForm(forms.Form):
    addiction = forms.ChoiceField(
        widget=forms.RadioSelect(),
        choices=[
            (
                addiction.pk,
                format_html(
                    '<span><img src="/media/{}" width="42" height="42"/> &nbsp;&nbsp;&nbsp;&nbsp;{}</span>'
                    .format(addiction.icon, addiction.name))
            )
            for addiction in Addiction.objects.all()
        ]
    )

    time = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Wybierz godzinę',
                'data-default': '{}:{}'.format(leading_zero(datetime.now().hour), leading_zero(datetime.now().minute)),
                'value': '{}:{}'.format(leading_zero(datetime.now().hour), leading_zero(datetime.now().minute)),
            }
        )
    )

    date = forms.CharField(
        label='Wybierz datę',
        widget=forms.DateInput(
            attrs={
                'class': 'input-top form-control',
                'placeholder': 'Wybierz datę',
                'data-provide': 'datepicker',
                'data-date-autoclose': 'true',
                'data-date-format': 'dd/mm/yyyy',
                'data-date-clear-btn': 'true',
                'data-date-language': 'pl',
                'value': '{}/{}/{}'.format(
                    leading_zero(datetime.now().day),
                    leading_zero(datetime.now().month),
                    datetime.now().year
                ),
            },
            format='%d/%m/%Y'
        )
    )

    motive = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': '4',
                'cols': '40',
                'placeholder': 'np. oszczędność czasu, pieniędzy',
            }
        )
    )

    def clean_addiction(self):
        addiction = self.cleaned_data['addiction']
        try:
            addiction = Addiction.objects.get(pk=int(addiction))
        except:
            raise forms.ValidationError('Wybierz poprawny nałóg')
        return addiction

    def clean_time(self):
        try:
            time = self.cleaned_data['time']
            format_str = '%H:%M'
            time = datetime.strptime(time, format_str)
        except:
            raise forms.ValidationError('Wprowadź poprawną godzinę')
        return time

    def clean_date(self):
        try:
            date = self.cleaned_data['date']
            format_str = '%d/%m/%Y'
            date = datetime.strptime(date, format_str)
        except:
            raise forms.ValidationError('Wprowadź poprawną datę')

        try:
            time = self.cleaned_data['time']
            full_date = datetime(date.year, date.month, date.day, time.hour, time.minute)
            if full_date > datetime.now():
                raise Exception
        except:
            raise forms.ValidationError('Data powinna być wcześniejsza niż obecna')

        return date

    def clean_motive(self):
        motive = self.cleaned_data['motive']
        if len(motive) < 6:
            raise forms.ValidationError('Tekst powinien zawierać minimum 6 znaków')
        return motive

    def start_path(self, user):
        addiction = self.cleaned_data['addiction']
        time = self.cleaned_data['time']
        date = self.cleaned_data['date']
        motive = self.cleaned_data['motive']

        full_date = datetime(date.year, date.month, date.day, time.hour, time.minute)

        path = Quitpath.objects.create(user=user, addiction=addiction, motive=motive, last_breakpoint_date=full_date)
        breakpoint = Breakpoint.objects.create(date=str(full_date), quitpath=path)

        prepare_trophies(path)


class BreakpointForm(forms.Form):
    time = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Wybierz godzinę',
                'data-default': '{}:{}'.format(leading_zero(datetime.now().hour), leading_zero(datetime.now().minute)),
                'value': '{}:{}'.format(leading_zero(datetime.now().hour), leading_zero(datetime.now().minute)),
            }
        )
    )

    date = forms.CharField(
        label='Wybierz datę',
        widget=forms.DateInput(
            attrs={
                'class': 'input-top form-control',
                'placeholder': 'Wybierz datę',
                'data-provide': 'datepicker',
                'data-date-autoclose': 'true',
                'data-date-format': 'dd/mm/yyyy',
                'data-date-clear-btn': 'true',
                'data-date-language': 'pl',
                'value': '{}/{}/{}'.format(
                    leading_zero(datetime.now().day),
                    leading_zero(datetime.now().month),
                    datetime.now().year
                ),
            },
            format='%d/%m/%Y'
        )
    )

    def clean_time(self):
        try:
            time = self.cleaned_data['time']
            format_str = '%H:%M'
            time = datetime.strptime(time, format_str)
        except:
            raise forms.ValidationError('Wprowadź poprawną godzinę')
        return time

    def clean_date(self):
        try:
            date = self.cleaned_data['date']
            format_str = '%d/%m/%Y'
            date = datetime.strptime(date, format_str)
        except:
            raise forms.ValidationError('Wprowadź poprawną datę')

        try:
            time = self.cleaned_data['time']
            full_date = datetime(date.year, date.month, date.day, time.hour, time.minute)
            if full_date > datetime.now():
                raise Exception
        except:
            raise forms.ValidationError('Data powinna być wcześniejsza niż obecna')

        return date

    def create_breakpoint(self, path):
        time = self.cleaned_data['time']
        date = self.cleaned_data['date']

        full_date = datetime(date.year, date.month, date.day, time.hour, time.minute)
        _ = Breakpoint.objects.create(date=str(full_date), quitpath=path)
        latest = Breakpoint.objects.filter(quitpath=path).latest('date')

        path.last_breakpoint_date = latest.date
        path.save()

apps/quitpath/views.py
import json
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from dateutil.relativedelta import relativedelta
from django.urls import reverse

from apps.quitpath.models import Quitpath, Trophy
from apps.quitpath.utils import get_longest_time, get_dates, MONTHS, find_best_trophy, reset_trophies
from .forms import QuitpathForm, Breakpoint, BreakpointForm


@login_required
def paths(request):
    paths = list()

    for path in Quitpath.objects.filter(user=request.user):
        _, actual_total_seconds = get_longest_time(path.pk)

        paths.append({
            'data': get_dates(path.pk),
            'path': path,
            'trophy': find_best_trophy(path),
            'actual_total_seconds': actual_total_seconds
        })

    context = {
        'paths': paths
    }
    return render(request, 'paths.html', context)


@login_required
def new_path(request):
    if request.method == 'POST':
        form = QuitpathForm(request.POST)
        if form.is_valid():
            form.start_path(request.user)
            return redirect('paths')
    else:
        form = QuitpathForm()
    context = {
        'form': form
    }
    return render(request, 'new_path.html', context)


@login_required
def quitpath(request, id):
    quitpath = get_object_or_404(Quitpath, pk=id)

    if request.method == 'POST':
        form = BreakpointForm(request.POST)
        if form.is_valid():
            form.create_breakpoint(quitpath)
            reset_trophies(quitpath)
            return redirect('quitpath', id=id)
    else:
        form = BreakpointForm()

    now = datetime.now()
    delta = relativedelta(now, quitpath.last_breakpoint_date)

    if request.GET.get('month') and request.GET.get('year'):
        try:
            month = int(request.GET['month'])
            year = int(request.GET['year'])
        except:
            month = now.month
            year = now.year
    else:
        month = now.month
        year = now.year
    cal_date = datetime(day=1, month=month, year=year)

    prev_month = cal_date - relativedelta(months=1)
    next_month = cal_date + relativedelta(months=1)

    calendar = []
    row = list()

    breakpoints = {}

    for breakpoint in Breakpoint.objects.filter(quitpath=quitpath):
        date = '{}-{}-{}'.format(breakpoint.date.day, breakpoint.date.month, breakpoint.date.year)

        try:
            _ = breakpoints[date]
        except:
            breakpoints[date] = []

        breakpoints[date].append(breakpoint)

    while cal_date.month != next_month.month:
        date = '{}-{}-{}'.format(cal_date.day, cal_date.month, cal_date.year)
        day = {
            'date': date,
            'day': cal_date.day,
            'breakpoints': sorted(breakpoints.get(date, list()), key=lambda x: x.date),
            'count': len(breakpoints.get(date, list()))
        }

        if cal_date == datetime(day=now.day, month=now.month, year=now.year):
            day['today'] = True

        row.append(day)

        if cal_date.weekday() == 6:
            calendar.append(row)
            row = list()

        cal_date += timedelta(days=1)

    if row:
        calendar.append(row)

    if len(calendar[0]) != 7:
        calendar[0] = [None for _ in range(7 - len(calendar[0]))] + calendar[0]
    if len(calendar[-1]) != 7:
        calendar[-1] = calendar[-1] + [None for _ in range(7 - len(calendar[-1]))]

    longest, actual_total_seconds = get_longest_time(id)

    context = {
        'id': id,
        'quitpath': quitpath,
        'today': {
            'month': MONTHS[month],
            'year': year
        },
        'begin_date': quitpath.begin_date.strftime('%d-%m-%Y'),
        'last_breakpoint_date': quitpath.last_breakpoint_date.strftime('%H:%M %d-%m-%Y'),
        'abst': delta,
        'calendar': calendar,
        'next_month': next_month,
        'prev_month': prev_month,
        'longest': longest,
        'actual_total_seconds': actual_total_seconds,
        'form': form,
        'trophies': Trophy.objects.filter(quitpath=quitpath).order_by('time').values()
    }

    return render(request, 'quitpath.html', context)


@login_required
def delete_breakpoint(request, quitpath_id, breakpoint_id):
    breakpoint = get_object_or_404(Breakpoint, pk=breakpoint_id)
    quitpath = get_object_or_404(Quitpath, pk=quitpath_id)

    breakpoint.delete()

    quitpath.last_breakpoint_date = Breakpoint.objects.filter(quitpath=quitpath).latest('date').date
    quitpath.save()
    reset_trophies(quitpath)

    return HttpResponseRedirect(reverse('quitpath', kwargs={'id': quitpath_id}))


@login_required
def gettime(request, id):
    return HttpResponse(json.dumps(get_dates(id)), content_type='application/json')


@login_required
def get_best_trophy(request, id):
    path = get_object_or_404(Quitpath, pk=id)

    best_trophy = find_best_trophy(path)
    best_trophy['actual_total_seconds'] = (datetime.now() - path.last_breakpoint_date).total_seconds()

    return HttpResponse(json.dumps(best_trophy), content_type='application/json')


@login_required
def delete_quitpath(request, id):
    quitpath = get_object_or_404(Quitpath, pk=id)
    quitpath.delete()
    return HttpResponseRedirect(reverse('paths'))

apps/quitpath/templates/new_path.html
{% extends 'base.html' %}

{% block title %}ChainBreak  - moje ścieżki{% endblock %}

{% block additional_data %}
    <link rel="stylesheet" href="/static/clockpicker/dist/jquery-clockpicker.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
{% endblock %}


{% block additional_js %}
    <script src="/static/clockpicker/dist/jquery-clockpicker.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <script>
        $.fn.datepicker.dates['pl'] = {
            days: ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"],
            daysShort: ["Nie", "Pon", "Wt", "Śr", "Czw", "Pt", "Sob"],
            daysMin: ["Nie", "Pon", "Wt", "Śr", "Czw", "Pt", "Sob"],
            months: ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
            monthsShort: ["Sty", "Lut", "Mar", "Kwi", "Maj", "Czer", "Lip", "Sie", "Wrz", "Paź", "Lis", "Gru"],
            today: "Dziś",
            clear: "Wyczyść",
            format: "dd/mm/yyyy",
            titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
            weekStart: 1
        };

        var input = $('#id_time');
        input.clockpicker({
            autoclose: true
        });

        $("#which").hide();
        setTimeout(function() {
            $("#which").show('slow');
        }, 0);

        $("#when").hide();
        setTimeout(function() {
            $("#when").show('slow');
        }, 200);

        $("#why").hide();
        setTimeout(function() {
            $("#why").show('slow');
        }, 400);

        $("#start").hide();
        setTimeout(function() {
            $("#start").show('slow');
        }, 600);
    </script>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'new_path' %}">{% csrf_token %}
	<h1>Nowa ścieżka</h1><br><br>
	<div class="row">
        <div class="col-4 text-center">
            <h3>Jaki nałóg chcesz zwalczyć?</h3>
        </div>
        <div class="col-4 text-center">
            <h3>Kiedy był ostatni raz?</h3>
        </div>
        <div class="col-4 text-center">
            <h3>W jaki sposób motywujesz chęć zwalczenia nałogu?</h3>
        </div>
    </div>
	<div class="row">
        <div class="col-4 text-center">
            <div id="which" class="card card-margin equal-card card-highlight">
                <div class="card-body">
                    <div style="overflow-y: scroll; height:150px;">
                        {{ form.addiction }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <div id="when" class="card card-margin equal-card card-highlight">
                <div class="card-body">
                    {{ form.time }}<br>
                    {{ form.date }}
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <div id="why" class="card card-margin equal-card card-highlight">
                <div class="card-body">
                    {{ form.motive }}
                </div>
            </div>
        </div>
    </div>
    {% if form.errors %}
        <div class="row">
            <div class="col-4 text-center">
                {% for error in form.addiction.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="col-4 text-center">
                {% for error in form.time.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
                {% for error in form.date.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
            <div class="col-4 text-center">
                {% for error in form.motive.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="offset-4 col-4">
            <br>
            <div class="card-margin">
                <input id="start" type="submit" class="btn btn-success btn-block" value="Rozpocznij" />
            </div>
        </div>
	</div>
</form>
{% endblock %}

apps/quitpath/templates/paths.html
{% extends 'base.html' %}

{% block title %}ChainBreak  - moje ścieżki{% endblock %}

{% block additional_js %}
    <script src="/static/clockpicker/dist/jquery-clockpicker.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript" src="http://www.gerardolarios.com/plugins-and-tools/jqmeter/js/jqmeter.min.js"></script>
    <script>
        function setTrophies() {
        	{% for path in paths %}
				$.get("{% url 'gettime' id=path.path.pk %}", function(data) {
					var delta = data.delta;
					var actual = "";
					if(delta.years !== 0) actual += delta.years + " lat "
					if(delta.months !== 0) actual += delta.months + " msc "
					if(delta.days !== 0) actual += delta.days + " dni "
					actual += delta.hours + " h "
					actual += delta.minutes + " min";
					$("#abst_time{{ path.path.pk }}").text(actual);
				});

				$.get("{% url 'get_best_trophy' id=path.path.pk %}", function(data) {
					var actual_total_seconds = Math.floor(data.actual_total_seconds);

					percentage = actual_total_seconds / Math.floor({{ path.trophy.time }}) * 100;
					percentage = Math.min(percentage, 100.00);
					percentage = percentage.toFixed(2) + "%";

					$("#percentage{{ path.path.id }}").text(percentage);

					var val2 = Math.floor({{ path.trophy.time }}).toString();
					var val1 = Math.min(actual_total_seconds, Math.floor({{ path.trophy.time }})).toString();

					var id = "#time" + "{{ path.path.id }}";
					$(id).jQMeter({
						goal: val2,
						raised: val1,
						meterOrientation:'horizontal',
						width:'100%',
						height:'25px',
						displayTotal: false,
						animationSpeed: 1
					});
				});

			{% endfor %}
        }

        setInterval(function() {
        	setTrophies()
        }, 15000);

        setTrophies();

    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12 clearfix">
            <div class="float-left ml-3">
                <h1>Moje ścieżki</h1>
            </div>
            <div class="float-right mr-3">
                <a href="{% url 'new_path' %}" class="btn btn-info">Nowa ścieżka</a>
            </div>
        </div>
    </div>

    <hr/>

	<div class="row">
		<div class="offset-1 col-10">
            {% if not paths %}
                <h2>Brak prowadzonych ścieżek</h2>
                <a href="{% url 'new_path' %}">Rozpocznij nową ścieżkę</a>
            {% else %}
				{% for path in paths %}
					<div id="when" class="card card-margin equal-card card-highlight">
						<div class="card-body">
							<div>
								<a href="{% url 'quitpath' id=path.path.id %}" class="title-hover float-left"><h2 class="spacing-header">
									{{ path.path.addiction.name }}</h2>
								</a>
								<button type="button" class="btn btn-danger btn-sm float-right" data-toggle="modal" data-target="#deletePath{{ path.path.pk }}">
									Usuń
								</button>
								<div class="modal" id="deletePath{{ path.path.pk }}">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-body">
												<p>Czy na pewno chcesz usunąć ścieżkę?</p>
											</div>
											<div class="modal-footer">
												<button class="btn btn-info" data-dismiss="modal">Powrót</button>
												<a href="{% url 'delete_quitpath' id=path.path.pk %}" class="btn btn-danger">Usuń</a>
											</div>
										</div>
									</div>
								</div>
							</div>
							<table class="table calendar-table">
								<tbody class="table-sm">
									<tr>
										<td style="white-space: nowrap; width: 1px;">
											<b>Motywacja:</b>
											<p style="margin-left: 20px; margin-right: 20px;">
												{{ path.path.motive }}
											</p>

											<b>Abstynencja:</b>
											<p style="margin-left: 20px; margin-right: 20px;">
												<span id="abst_time{{ path.path.pk }}">
													{% if path.data.delta.years %}
														{{ path.data.delta.years }} lat
													{% endif %}
													{% if path.data.delta.months %}
														{{ path.data.delta.months }} msc
													{% endif %}
													{% if path.data.delta.days %}
														{{ path.data.delta.days }} dni
													{% endif %}
													{{ path.data.delta.hours }} h
													{{ path.data.delta.minutes }} min
												</span>
											</p>
										</td>
										<td style="white-space: nowrap; width: 1px;">
											<br>
											<img src="{{ path.trophy.icon }}" width="64" height="64">&nbsp;&nbsp;&nbsp;&nbsp;
										</td>
										<td class="text-center">
											<p id="percentage{{ path.path.id }}">{{ path.trophy.elapsed }}</p>
											<div id="time{{ path.path.id }}"></div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div><br>
				{% endfor %}
            {% endif %}
		</div>
	</div>
{% endblock %}